blank_issues_enabled: true
contact_links:
    - name: Dataverse Community Support
      url: https://chat.dataverse.org/
      about: Please ask and answer questions here.
    - name: Dataverse Security Issues
      url: mailto:security@dataverse.org
      about: Please report security vulnerabilities here.
